package pipeline

import (
	"bonsai-tui/internal/config"
	"bonsai-tui/internal/pipeline/packer"
	"bytes"
	"encoding/binary"
	"fmt"
	"image/png"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

// raw bytes for hot reload
type HotReloadPayload struct {
	PngBytes    []byte
	MetadataBin []byte
}

type SpriteMetadata struct {
	U0, V0, U1, V1 float32
	SizeX, SizeY   float32
	Frames         int32
}

func getMsdfGenPlatformDetails() (url string, filename string, err error) {
	baseURL := "https://github.com/nihiL7331/bonsai-tools-bin/releases/download/v1.0/"

	var path string
	var exec string
	switch runtime.GOOS {
	case "windows":
		path = "msdf-atlas-gen-windows.exe"
		exec = "msdf-atlas-gen.exe"
	case "linux":
		path = "msdf-atlas-gen-linux"
		exec = "msdf-atlas-gen"
	case "darwin":
		path = "msdf-atlas-gen-macos-arm64"
		exec = "msdf-atlas-gen"
	default:
		return "", "", fmt.Errorf("Unsupported platform: %s", runtime.GOOS)
	}

	return baseURL + path, exec, nil
}

func EnsureMsdfGen(logFn func(string, string)) (string, error) {
	url, filename, err := getMsdfGenPlatformDetails()
	if err != nil {
		return "", err
	}

	cacheDir, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("Cache directory not found: %w", err)
	}

	installDir := filepath.Join(cacheDir, "bonsai", "bin")
	destPath := filepath.Join(installDir, filename)

	if _, err := os.Stat(destPath); err == nil {
		return destPath, nil
	}

	if err := os.MkdirAll(installDir, 0755); err != nil {
		return "", fmt.Errorf("Failed to create install directory: %w", err)
	}

	logFn("TOOLS", "Downloading msdf-atlas-gen...")

	resp, err := http.Get(url)
	if err != nil {
		return "", fmt.Errorf("Failed to request msdf-atlas-gen: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("Failed to download msdf-atlas-gen, status code: %d", resp.StatusCode)
	}

	out, err := os.Create(destPath)
	if err != nil {
		return "", err
	}
	defer out.Close()

	if _, err := io.Copy(out, resp.Body); err != nil {
		return "", fmt.Errorf("Failed to write binary to disk: %w", err)
	}

	os.Chmod(destPath, 0o755)

	return destPath, nil
}

func generateSpriteMetadata(
	sprites []packer.PlacedSprite,
	atlasWidth, atlasHeight int,
	odinOutputDir, binOutputDir string,
) ([]byte, error) {
	var odin strings.Builder

	odin.WriteString("// NOTE: Machine generated by bonsai TUI.\n")
	odin.WriteString("package generated\n\n")
	odin.WriteString("// @overview\n")
	odin.WriteString("// This package contains all of the auto-generated data at build-time. Currently it stores:\n")
	odin.WriteString("// - **Sprite data:** Assigns **atlas UV** and **image size in pixels** to every **PNG** image from **assets/images**.\n")
	odin.WriteString("//   Manages animation and tileset data. More information on that topic can be found [here](`https://bonsai-framework.dev/reference/core/render/#overview`).\n")
	odin.WriteString("// - **Font data:** Grabs **TTF/OTF** files present in the `assets/fonts` directory, generates bitmap using the [`stb`](`https://github.com/nothings/stb`) library.\n")
	odin.WriteString("//   Makes the fonts easily accessible with the [`FontName`](#fontname) enum.\n")
	odin.WriteString("// - **Audio data:** Grabs **WAV** files present in the `assets/audio` directory and links each sound to a [`SoundName`](#soundname) enum.\n")
	odin.WriteString("// - **Scene data:** Generates a registry in the `source/game/scenes` directory, which registers all created scenes. Using directory names, generates\n")
	odin.WriteString("//   a [`SceneName`](#scenename) enum to access them. Example usage can be found [here](`https://bonsai-framework.dev/reference/core/scene/#overview`).\n\n")
	odin.WriteString("import \"bonsai:core/gmath\"\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Struct assigned to every sprite present on the atlas.\n")
	odin.WriteString("SpriteData :: struct {\n")
	odin.WriteString("\tuv:           gmath.Vector4,\n")
	odin.WriteString("\tsize:         gmath.Vector2,\n")
	odin.WriteString("\tframes:       i32,\n")
	odin.WriteString("}\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Enum containing all sprite file names.\n")
	odin.WriteString("SpriteName :: enum u32 {\n")
	odin.WriteString("\tnil,\n")

	metadataArray := []SpriteMetadata{
		{U0: 0, V0: 0, U1: 0, V1: 0, SizeX: 0, SizeY: 0, Frames: 1},
	}

	for _, sprite := range sprites {
		baseName := strings.TrimSuffix(sprite.Name, filepath.Ext(sprite.Name))
		cleanKey := strings.ReplaceAll(baseName, "-", "_")
		cleanKey = strings.ReplaceAll(cleanKey, " ", "_")

		cleanKey = cleanKeySuffix(cleanKey)

		odin.WriteString(fmt.Sprintf("\t%s,\n", cleanKey))

		u0 := float32(sprite.Rect.X) / float32(atlasWidth)
		v0 := float32(sprite.Rect.Y) / float32(atlasHeight)
		u1 := float32(sprite.Rect.X+sprite.Rect.W) / float32(atlasWidth)
		v1 := float32(sprite.Rect.Y+sprite.Rect.H) / float32(atlasHeight)

		framesCount := int32(1.0)
		if lastUnderscore := strings.LastIndex(cleanKey, "_"); lastUnderscore != -1 {
			suffix := cleanKey[lastUnderscore+1:]
			if xIdx := strings.Index(suffix, "x"); xIdx != -1 {
				framesStr := suffix[:xIdx]
				if parsed, err := strconv.ParseFloat(framesStr, 32); err == nil {
					framesCount = int32(parsed)
				}
			}
		}

		metadataArray = append(metadataArray, SpriteMetadata{
			U0: u0, V0: v0, U1: u1, V1: v1,
			SizeX:  float32(sprite.Rect.W),
			SizeY:  float32(sprite.Rect.H),
			Frames: framesCount,
		})
	}
	odin.WriteString("}\n\n")

	if err := os.MkdirAll(filepath.Dir(odinOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(odinOutputDir, []byte(odin.String()), 0o644); err != nil {
		return nil, err
	}

	binBuf := new(bytes.Buffer)
	for _, meta := range metadataArray {
		binary.Write(binBuf, binary.LittleEndian, meta.U0)
		binary.Write(binBuf, binary.LittleEndian, meta.V0)
		binary.Write(binBuf, binary.LittleEndian, meta.U1)
		binary.Write(binBuf, binary.LittleEndian, meta.V1)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeX)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeY)
		binary.Write(binBuf, binary.LittleEndian, meta.Frames)
	}

	if err := os.MkdirAll(filepath.Dir(binOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(binOutputDir, binBuf.Bytes(), 0o644); err != nil {
		return nil, err
	}

	return binBuf.Bytes(), nil
}

func PackAtlas(cfg config.Config, logFn func(string, string)) (*HotReloadPayload, error) {
	imagesDir := getImagesDir(cfg)
	atlasDir := getAtlasCacheDir(cfg)
	atlasPath := filepath.Join(atlasDir, "atlas.png")

	if !isDirNewer(imagesDir, atlasPath) {
		logFn("ATLAS", "Atlas is up to date. Skipping packing.")
		return nil, nil
	}

	files, err := getSortedImageFiles(imagesDir)
	if err != nil {
		return nil, fmt.Errorf("Failed to read images: %w", err)
	}

	odinOutDir := getOdinAtlasDir(cfg)
	binOutDir := getBinAtlasDir(cfg)

	if len(files) == 0 {
		_, err := generateSpriteMetadata(nil, 2048, 2048, odinOutDir, binOutDir)
		if err != nil {
			return nil, err
		}
		logFn("ATLAS", "No images to pack. Skipping packing.")
		return nil, nil
	}

	logFn("ATLAS", "Packing texture atlas...")

	pckr := packer.NewPacker(2048, 2048)

	placedSprites, err := processImages(files, pckr, logFn)
	if err != nil {
		return nil, fmt.Errorf("Failed to process images: %w", err)
	}

	pngBytes, err := packer.RenderAtlas(2048, 2048, placedSprites)
	if err != nil {
		return nil, fmt.Errorf("Failed to render atlas: %w", err)
	}

	if err := os.WriteFile(atlasPath, pngBytes, 0o644); err != nil {
		return nil, fmt.Errorf("Failed to write 'atlas.png': %w", err)
	}

	metadataBin, err := generateSpriteMetadata(
		placedSprites,
		2048,
		2048,
		odinOutDir,
		binOutDir,
	)
	if err != nil {
		return nil, fmt.Errorf("Failed to generate metadata: %w", err)
	}

	return &HotReloadPayload{
		PngBytes:    pngBytes,
		MetadataBin: metadataBin,
	}, nil
}

// grabs all .png files within 'dir'
// and sorts them alphabetically
func getSortedImageFiles(dir string) ([]string, error) {
	var files []string

	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if strings.ToLower(filepath.Ext(path)) == ".png" {
			files = append(files, path)
		}
		return nil
	})

	sort.Strings(files)
	return files, err
}

func processImages(files []string, pckr *packer.MaxRectsPacker, logFn func(string, string)) ([]packer.PlacedSprite, error) {
	var placedSprites []packer.PlacedSprite
	padding := 2

	for _, file := range files {
		w, h, err := getImageDimensions(file)
		if err != nil {
			return nil, err
		}

		rect := pckr.Insert(w+padding, h+padding)
		if rect.W == 0 {
			return nil, fmt.Errorf("Atlas is full. Could not fit: %s", filepath.Base(file))
		}

		placedSprites = append(placedSprites, packer.PlacedSprite{
			Name: filepath.Base(file),
			Path: file,
			Rect: packer.Rect{
				X: rect.X + (padding / 2),
				Y: rect.Y + (padding / 2),
				W: w,
				H: h,
			},
		})
	}

	return placedSprites, nil
}

// reads header of a PNG file to get image size
func getImageDimensions(path string) (width int, height int, err error) {
	file, err := os.Open(path)
	if err != nil {
		return 0, 0, err
	}
	defer file.Close()

	config, err := png.DecodeConfig(file)
	if err != nil {
		return 0, 0, err
	}
	return config.Width, config.Height, nil
}

// removes dimension suffixes
func cleanKeySuffix(cleanKey string) string {
	lastUnderscore := strings.LastIndex(cleanKey, "_")
	if lastUnderscore != -1 {
		suffix := cleanKey[lastUnderscore+1:]

		xIdx := strings.Index(suffix, "x")
		if xIdx != -1 {
			left := suffix[:xIdx]
			right := suffix[xIdx+1:]

			_, errLeft := strconv.Atoi(left)
			_, errRight := strconv.Atoi(right)

			if errLeft == nil && errRight == nil {
				return cleanKey[:lastUnderscore]
			}
		}
	}

	return cleanKey
}
