package pipeline

import (
	"bonsai-tui/internal/pipeline/packer"
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// raw bytes for hot reload
type HotReloadPayload struct {
	PngBytes    []byte
	MetadataBin []byte
}

type SpriteMetadata struct {
	U0, V0, U1, V1 float32
	SizeX, SizeY   float32
	Frames         int32
}

func generateSpriteMetadata(
	sprites []packer.PlacedSprite,
	atlasWidth, atlasHeight int,
	odinOutputDir, binOutputDir string,
) ([]byte, error) {
	var odin strings.Builder

	odin.WriteString("// NOTE: Machine generated by bonsai TUI.\n")
	odin.WriteString("package generated\n\n")
	odin.WriteString("// @overview\n")
	odin.WriteString("// This package contains all of the auto-generated data at build-time. Currently it stores:\n")
	odin.WriteString("// - **Sprite data:** Assigns **atlas UV** and **image size in pixels** to every **PNG** image from **assets/images**.\n")
	odin.WriteString("//   Manages animation and tileset data. More information on that topic can be found [here](`https://bonsai-framework.dev/reference/core/render/#overview`).\n")
	odin.WriteString("// - **Font data:** Grabs **TTF/OTF** files present in the `assets/fonts` directory, generates bitmap using the [`stb`](`https://github.com/nothings/stb`) library.\n")
	odin.WriteString("//   Makes the fonts easily accessible with the [`FontName`](#fontname) enum.\n")
	odin.WriteString("// - **Audio data:** Grabs **WAV** files present in the `assets/audio` directory and links each sound to a [`SoundName`](#soundname) enum.\n")
	odin.WriteString("// - **Scene data:** Generates a registry in the `source/game/scenes` directory, which registers all created scenes. Using directory names, generates\n")
	odin.WriteString("//   a [`SceneName`](#scenename) enum to access them. Example usage can be found [here](`https://bonsai-framework.dev/reference/core/scene/#overview`).\n\n")
	odin.WriteString("import \"bonsai:core/gmath\"\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Struct assigned to every sprite present on the atlas.\n")
	odin.WriteString("SpriteData :: struct {\n")
	odin.WriteString("\tuv:           gmath.Vector4,\n")
	odin.WriteString("\tsize:         gmath.Vector2,\n")
	odin.WriteString("\tframes:       i32,\n")
	odin.WriteString("}\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Enum containing all sprite file names.\n")
	odin.WriteString("SpriteName :: enum u32 {\n")
	odin.WriteString("\tnil,\n")

	metadataArray := []SpriteMetadata{
		{U0: 0, V0: 0, U1: 0, V1: 0, SizeX: 0, SizeY: 0, Frames: 1},
	}

	for _, sprite := range sprites {
		baseName := strings.TrimSuffix(sprite.Name, filepath.Ext(sprite.Name))
		cleanKey := strings.ReplaceAll(baseName, "-", "_")
		cleanKey = strings.ReplaceAll(cleanKey, " ", "_")

		cleanKey = cleanKeySuffix(cleanKey)

		odin.WriteString(fmt.Sprintf("\t%s,\n", cleanKey))

		u0 := float32(sprite.Rect.X) / float32(atlasWidth)
		v0 := float32(sprite.Rect.Y) / float32(atlasHeight)
		u1 := float32(sprite.Rect.X+sprite.Rect.W) / float32(atlasWidth)
		v1 := float32(sprite.Rect.Y+sprite.Rect.H) / float32(atlasHeight)

		framesCount := int32(1.0)
		if lastUnderscore := strings.LastIndex(cleanKey, "_"); lastUnderscore != -1 {
			suffix := cleanKey[lastUnderscore+1:]
			if xIdx := strings.Index(suffix, "x"); xIdx != -1 {
				framesStr := suffix[:xIdx]
				if parsed, err := strconv.ParseFloat(framesStr, 32); err == nil {
					framesCount = int32(parsed)
				}
			}
		}

		metadataArray = append(metadataArray, SpriteMetadata{
			U0: u0, V0: v0, U1: u1, V1: v1,
			SizeX:  float32(sprite.Rect.W),
			SizeY:  float32(sprite.Rect.H),
			Frames: framesCount,
		})
	}
	odin.WriteString("}\n\n")

	if err := os.MkdirAll(filepath.Dir(odinOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(odinOutputDir, []byte(odin.String()), 0o644); err != nil {
		return nil, err
	}

	binBuf := new(bytes.Buffer)
	for _, meta := range metadataArray {
		binary.Write(binBuf, binary.LittleEndian, meta.U0)
		binary.Write(binBuf, binary.LittleEndian, meta.V0)
		binary.Write(binBuf, binary.LittleEndian, meta.U1)
		binary.Write(binBuf, binary.LittleEndian, meta.V1)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeX)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeY)
		binary.Write(binBuf, binary.LittleEndian, meta.Frames)
	}

	if err := os.MkdirAll(filepath.Dir(binOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(binOutputDir, binBuf.Bytes(), 0o644); err != nil {
		return nil, err
	}

	return binBuf.Bytes(), nil
}
