package pipeline

import (
	"bonsai-tui/internal/config"
	"bonsai-tui/internal/engine"
	"bonsai-tui/internal/pipeline/packer"
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type assetEntry struct {
	CleanName string
	FilePath  string
}

// raw bytes for hot reload
type HotReloadPayload struct {
	PngBytes    []byte
	MetadataBin []byte
}

type SpriteMetadata struct {
	U0, V0, U1, V1 float32
	SizeX, SizeY   float32
	Frames         int32
}

// processes all fonts, audio, and scenes, and generates odin metadata
func GenerateAssets(cfg config.Config, msdfExe string, logFn func(string, string)) error {
	logFn("PIPELINE", "Generating asset metadata...")

	fontSrcDir := filepath.Join(cfg.GetAssetsDir(), engine.FontsDir)
	fontOutDir := filepath.Join(getEngineDir(cfg), engine.GeneratedDir)
	fontDataOutDir := getFontCacheDir(cfg)

	audioSrcDir := filepath.Join(cfg.GetAssetsDir(), engine.AudioDir)
	audioOutDir := filepath.Join(getEngineDir(cfg), engine.GeneratedDir)

	sceneSrcDir := filepath.Join(cfg.GetGameDir(), cfg.ScenesDir)
	sceneOutDir := filepath.Join(getEngineDir(cfg), engine.GeneratedDir)
	sceneRegOutDir := sceneOutDir

	if _, err := buildFonts(fontSrcDir, fontDataOutDir, msdfExe, logFn); err != nil {
		return fmt.Errorf("Failed to build core fonts: %w", err)
	}
	// if payloads, err := buildFonts(fontSrcDir, fontDataOutDir, msdfExe, logFn); err != nil {
	// 	return fmt.Errorf("Failed to build core fonts: %w", err)
	// }

	// PixelCode font call
	if _, err := buildFonts(filepath.Join(getEngineDir(cfg), engine.DefaultFontName), fontDataOutDir, msdfExe, logFn); err != nil {
		return fmt.Errorf("Failed to build default font: %w", err)
	}

	err := generateAssetMetadata(
		fontSrcDir, fontOutDir,
		"additional_font", "additional_fonts.odin",
		[]string{".ttf", ".otf"},
		"font",
	)
	if err != nil {
		return fmt.Errorf("Failed to generate font metadata: %w", err)
	}

	err = generateAssetMetadata(
		audioSrcDir, audioOutDir,
		"", "",
		[]string{".wav"},
		"audio",
	)
	if err != nil {
		return fmt.Errorf("Failed to generate audio metadata: %w", err)
	}

	err = generateAssetMetadata(
		sceneSrcDir, sceneOutDir,
		"", "",
		nil,
		"scene",
	)
	if err != nil {
		return fmt.Errorf("Failed to generate scene metadata: %w", err)
	}

	if err := generateSceneRegMetadata(sceneSrcDir, sceneRegOutDir); err != nil {
		return fmt.Errorf("Failed to generate scene registry: %w", err)
	}

	return nil
}

func generateSpriteMetadata(
	sprites []packer.PlacedSprite,
	atlasWidth, atlasHeight int,
	odinOutputDir, binOutputDir string,
) ([]byte, error) {
	var odin strings.Builder

	odin.WriteString("// NOTE: Machine generated by bonsai TUI.\n")
	odin.WriteString("package generated\n\n")
	odin.WriteString("// @overview\n")
	odin.WriteString("// This package contains all of the auto-generated data at build-time. Currently it stores:\n")
	odin.WriteString("// - **Sprite data:** Assigns **atlas UV** and **image size in pixels** to every **PNG** image from **assets/images**.\n")
	odin.WriteString("//   Manages animation and tileset data. More information on that topic can be found [here](`https://bonsai-framework.dev/reference/core/render/#overview`).\n")
	odin.WriteString("// - **Font data:** Grabs **TTF/OTF** files present in the `assets/fonts` directory, generates bitmap using the [`stb`](`https://github.com/nothings/stb`) library.\n")
	odin.WriteString("//   Makes the fonts easily accessible with the [`FontName`](#fontname) enum.\n")
	odin.WriteString("// - **Audio data:** Grabs **WAV** files present in the `assets/audio` directory and links each sound to a [`SoundName`](#soundname) enum.\n")
	odin.WriteString("// - **Scene data:** Generates a registry in the `source/game/scenes` directory, which registers all created scenes. Using directory names, generates\n")
	odin.WriteString("//   a [`SceneName`](#scenename) enum to access them. Example usage can be found [here](`https://bonsai-framework.dev/reference/core/scene/#overview`).\n\n")
	odin.WriteString("import \"bonsai:core/gmath\"\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Struct assigned to every sprite present on the atlas.\n")
	odin.WriteString("SpriteData :: struct {\n")
	odin.WriteString("\tuv:           gmath.Vector4,\n")
	odin.WriteString("\tsize:         gmath.Vector2,\n")
	odin.WriteString("\tframes:       i32,\n")
	odin.WriteString("}\n\n")
	odin.WriteString("// @ref\n")
	odin.WriteString("// Enum containing all sprite file names.\n")
	odin.WriteString("SpriteName :: enum u32 {\n")
	odin.WriteString("\tnil,\n")

	metadataArray := []SpriteMetadata{
		{U0: 0, V0: 0, U1: 0, V1: 0, SizeX: 0, SizeY: 0, Frames: 1},
	}

	for _, sprite := range sprites {
		baseName := strings.TrimSuffix(sprite.Name, filepath.Ext(sprite.Name))
		cleanKey := strings.ReplaceAll(baseName, "-", "_")
		cleanKey = strings.ReplaceAll(cleanKey, " ", "_")

		cleanKey = cleanKeySuffix(cleanKey)

		odin.WriteString(fmt.Sprintf("\t%s,\n", cleanKey))

		u0 := float32(sprite.Rect.X) / float32(atlasWidth)
		v0 := float32(sprite.Rect.Y) / float32(atlasHeight)
		u1 := float32(sprite.Rect.X+sprite.Rect.W) / float32(atlasWidth)
		v1 := float32(sprite.Rect.Y+sprite.Rect.H) / float32(atlasHeight)

		framesCount := int32(1.0)
		if lastUnderscore := strings.LastIndex(cleanKey, "_"); lastUnderscore != -1 {
			suffix := cleanKey[lastUnderscore+1:]
			if xIdx := strings.Index(suffix, "x"); xIdx != -1 {
				framesStr := suffix[:xIdx]
				if parsed, err := strconv.ParseFloat(framesStr, 32); err == nil {
					framesCount = int32(parsed)
				}
			}
		}

		metadataArray = append(metadataArray, SpriteMetadata{
			U0: u0, V0: v0, U1: u1, V1: v1,
			SizeX:  float32(sprite.Rect.W),
			SizeY:  float32(sprite.Rect.H),
			Frames: framesCount,
		})
	}
	odin.WriteString("}\n\n")

	if err := os.MkdirAll(filepath.Dir(odinOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(odinOutputDir, []byte(odin.String()), 0o644); err != nil {
		return nil, err
	}

	binBuf := new(bytes.Buffer)
	for _, meta := range metadataArray {
		binary.Write(binBuf, binary.LittleEndian, meta.U0)
		binary.Write(binBuf, binary.LittleEndian, meta.V0)
		binary.Write(binBuf, binary.LittleEndian, meta.U1)
		binary.Write(binBuf, binary.LittleEndian, meta.V1)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeX)
		binary.Write(binBuf, binary.LittleEndian, meta.SizeY)
		binary.Write(binBuf, binary.LittleEndian, meta.Frames)
	}

	if err := os.MkdirAll(filepath.Dir(binOutputDir), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(binOutputDir, binBuf.Bytes(), 0o644); err != nil {
		return nil, err
	}

	return binBuf.Bytes(), nil
}

// scans a directory and outputs odin enums
// if exts == nil, searches for directories
func generateAssetMetadata(
	assetSrc string,
	assetOut string,
	additionalEnum string,
	additionalFilename string,
	exts []string,
	enumName string,
) error {
	var entries []assetEntry

	if _, err := os.Stat(assetSrc); err == nil {
		dirEntries, err := os.ReadDir(assetSrc)
		if err != nil {
			return fmt.Errorf("Failed to read asset directory %s: %w", assetSrc, err)
		}

		for _, entry := range dirEntries {
			isMatch := false

			if len(exts) > 0 {
				if !entry.IsDir() {
					ext := strings.ToLower(filepath.Ext(entry.Name()))
					for _, validExt := range exts {
						if ext == validExt {
							isMatch = true
							break
						}
					}
				}
			} else {
				if entry.IsDir() {
					isMatch = true
				}
			}

			if isMatch {
				baseName := strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name()))
				cleanName := strings.ReplaceAll(baseName, "-", "_")
				cleanName = strings.ReplaceAll(cleanName, " ", "_")

				if enumName == "font" {
					cleanName, _, _ = parseFontFilename(entry.Name())
				}

				fullPath := filepath.Join(assetSrc, entry.Name())
				odinPath := filepath.ToSlash(fullPath)

				entries = append(entries, assetEntry{
					CleanName: cleanName,
					FilePath:  odinPath,
				})
			}
		}
	}

	var sb strings.Builder

	sb.WriteString("// NOTE: Machine generated by bonsai TUI\n")
	sb.WriteString("package generated\n\n")
	sb.WriteString(fmt.Sprintf("// Contains all filename stems for %ss.\n", enumName))
	sb.WriteString(fmt.Sprintf("%s_name :: enum {\n", enumName))
	sb.WriteString("\tnil,\n")

	if additionalEnum != "" {
		sb.WriteString(fmt.Sprintf("\t%s,\n", additionalEnum))
	}
	for _, entry := range entries {
		sb.WriteString(fmt.Sprintf("\t%s,\n", entry.CleanName))
	}
	sb.WriteString("}\n\n")

	if len(exts) > 0 {
		sb.WriteString("// @ref\n")
		sb.WriteString(fmt.Sprintf("// Links every `%s_name` enum to its filepath.\n", enumName))
		sb.WriteString(fmt.Sprintf("%s_filename := [%s_name]string {\n", enumName, enumName))
		sb.WriteString("\t.nil = \"\",\n")

		if additionalEnum != "" {
			sb.WriteString(fmt.Sprintf("\t.%s = \"%s\",\n", additionalEnum, filepath.ToSlash(additionalFilename)))
		}
		for _, entry := range entries {
			sb.WriteString(fmt.Sprintf("\t.%s = \"%s\",\n", entry.CleanName, entry.FilePath))
		}
		sb.WriteString("}\n")
	}

	if err := os.MkdirAll(filepath.Dir(assetOut), 0o755); err != nil {
		return fmt.Errorf("Failed to create output directory: %w", err)
	}

	if err := os.WriteFile(assetOut, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("Failed to write Odin metadata file: %w", err)
	}

	return nil
}

// scans the scenes directory and wires up the Odin initialization code
func generateSceneRegMetadata(sceneSrc string, sceneOut string) error {
	var scenes []string

	if _, err := os.Stat(sceneSrc); err == nil {
		entries, err := os.ReadDir(sceneSrc)
		if err != nil {
			return fmt.Errorf("Faild to read scene directory: %w", err)
		}

		for _, entry := range entries {
			if entry.IsDir() {
				cleanName := strings.ReplaceAll(entry.Name(), "-", "_")
				cleanName = strings.ReplaceAll(entry.Name(), " ", "_")
				scenes = append(scenes, cleanName)
			}
		}
	}

	var sb strings.Builder

	sb.WriteString("// NOTE: Machine generated by bonsai TUI.\n")
	sb.WriteString("package scenes\n\n")

	sb.WriteString("import \"bonsai:core/scene\"")
	sb.WriteString("import \"bonsai:core/scene/type\"")
	sb.WriteString("import \"bonsai:gen\"")

	sb.WriteString("_ :: scene\n")
	sb.WriteString("_ :: gen\n")
	sb.WriteString("_ :: type\n\n")

	for _, name := range scenes {
		sb.WriteString(fmt.Sprintf("import \"%s\"\n", name))
	}
	sb.WriteString("\n")

	for _, name := range scenes {
		sb.WriteString(fmt.Sprintf("@(private = \"file\")\n_%s_data: %s.data", name, name))
	}
	sb.WriteString("\n")

	sb.WriteString("init_registry :: proc() {\n")
	for _, name := range scenes {
		sb.WriteString("\tscene.register(\n")
		sb.WriteString(fmt.Sprintf("\t\tgen.scene_name.%s,\n", name))
		sb.WriteString("\t\ttype.scene{\n")
		sb.WriteString(fmt.Sprintf("\t\t\tdata=&_%s_data,\n", name))
		sb.WriteString(fmt.Sprintf("\t\t\tinit=%s.init,\n", name))
		sb.WriteString(fmt.Sprintf("\t\t\tupdate=%s.update,\n", name))
		sb.WriteString(fmt.Sprintf("\t\t\tdraw=%s.draw,\n", name))
		sb.WriteString(fmt.Sprintf("\t\t\texit=%s.exit,\n", name))
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t)\n")
	}
	sb.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(sceneOut), 0o755); err != nil {
		return fmt.Errorf("Failed to create registry output directory: %w", err)
	}

	if err := os.WriteFile(sceneOut, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("Failed to write scene registry: %w", err)
	}

	return nil
}
